apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      #nodePort: 30005
  selector:
    name: result-app-pod
    app: demo-voting-app

